# Generated by Django 3.2.4 on 2021-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('price', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shopping/')),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
